import type { Sound } from './types';
import {
  Rain,
  Wave,
  Bird,
  Fire,
  Wind,
  Cricket,
  Thunder,
  Stream,
  MeditationBell,
  TibetanBowl,
  WindChimes,
  ForestNight,
  WhiteNoise,
  BrownNoise,
  Waterfall,
  CatPurr,
  OceanDeep,
  CoffeeShop,
  Heartbeat,
  Fan,
} from './components/icons';

export const SOUNDS: Sound[] = [
  // FREE SOUNDS
  {
    id: 'rain',
    name: 'Rain',
    icon: Rain,
    path: '/sounds/rain.mp3',
    isPremium: false,
    color: ['#4facfe', '#00f2fe'],
  },
  {
    id: 'waves',
    name: 'Ocean Waves',
    icon: Wave,
    path: '/sounds/waves.mp3',
    isPremium: false,
    color: ['#43e97b', '#38f9d7'],
  },
  {
    id: 'birds',
    name: 'Birds',
    icon: Bird,
    path: '/sounds/birds.mp3',
    isPremium: false,
    color: ['#fa709a', '#fee140'],
  },
  {
    id: 'fire',
    name: 'Fireplace',
    icon: Fire,
    path: '/sounds/fire.mp3',
    isPremium: false,
    color: ['#ff6b6b', '#ffa500'],
  },
  {
    id: 'wind',
    name: 'Wind',
    icon: Wind,
    path: '/sounds/wind.mp3',
    isPremium: false,
    color: ['#a8edea', '#fed6e3'],
  },

  // PREMIUM SOUNDS
  {
    id: 'crickets',
    name: 'Crickets',
    icon: Cricket,
    path: '/sounds/crickets.mp3',
    isPremium: true,
    color: ['#4b79a1', '#283e51'],
  },
  {
    id: 'thunder',
    name: 'Thunder',
    icon: Thunder,
    path: '/sounds/thunder.mp3',
    isPremium: true,
    color: ['#373b44', '#4286f4'],
  },
  {
    id: 'stream',
    name: 'Stream',
    icon: Stream,
    path: '/sounds/stream.mp3',
    isPremium: true,
    color: ['#2af598', '#009efd'],
  },
  {
    id: 'meditation-bell',
    name: 'Meditation Bell',
    icon: MeditationBell,
    path: '/sounds/meditation-bell.mp3',
    isPremium: true,
    color: ['#f093fb', '#f5576c'],
  },
  {
    id: 'tibetan-bowl',
    name: 'Tibetan Bowl',
    icon: TibetanBowl,
    path: '/sounds/tibetan-bowl.mp3',
    isPremium: true,
    color: ['#ffecd2', '#fcb69f'],
  },
  {
    id: 'wind-chimes',
    name: 'Wind Chimes',
    icon: WindChimes,
    path: '/sounds/wind-chimes.mp3',
    isPremium: true,
    color: ['#a1c4fd', '#c2e9fb'],
  },
  {
    id: 'forest-night',
    name: 'Forest Night',
    icon: ForestNight,
    path: '/sounds/forest-night.mp3',
    isPremium: true,
    color: ['#134e5e', '#71b280'],
  },
  {
    id: 'white-noise',
    name: 'White Noise',
    icon: WhiteNoise,
    path: '/sounds/white-noise.mp3',
    isPremium: true,
    color: ['#bdc3c7', '#2c3e50'],
  },
  {
    id: 'brown-noise',
    name: 'Brown Noise',
    icon: BrownNoise,
    path: '/sounds/brown-noice.mp3',
    isPremium: true,
    color: ['#8e7e6e', '#5d4e3e'],
  },
  {
    id: 'waterfall',
    name: 'Waterfall',
    icon: Waterfall,
    path: '/sounds/waterfall.mp3',
    isPremium: true,
    color: ['#667eea', '#764ba2'],
  },
  {
    id: 'cat',
    name: 'Cat Purring',
    icon: CatPurr,
    path: '/sounds/cat.mp3',
    isPremium: true,
    color: ['#f857a6', '#ff5858'],
  },
  {
    id: 'ocean-deep',
    name: 'Deep Ocean',
    icon: OceanDeep,
    path: '/sounds/ocean-deep.mp3',
    isPremium: true,
    color: ['#0f2027', '#2c5364'],
  },
  {
    id: 'coffee-shop',
    name: 'Coffee Shop',
    icon: CoffeeShop,
    path: '/sounds/coffee-shop.mp3',
    isPremium: true,
    color: ['#c79081', '#dfa579'],
  },
  {
    id: 'heartbeat',
    name: 'Heartbeat',
    icon: Heartbeat,
    path: '/sounds/heartbeat.mp3',
    isPremium: true,
    color: ['#ee0979', '#ff6a00'],
  },
  {
    id: 'fan',
    name: 'Fan',
    icon: Fan,
    path: '/sounds/fan.mp3',
    isPremium: true,
    color: ['#89f7fe', '#66a6ff'],
  },
];
